zapatacomputing/z-quantum-core

src/python/zquantum/core/bitstring_distribution.py, src/python/zquantum/core/bitstring_distribution_test.py, src/python/zquantum/core/circuit/_circuit_template_test.py, src/python/zquantum/core/interfaces/backend.py, src/python/zquantum/core/interfaces/mock_objects.py, src/python/zquantum/core/measurement.py, src/python/zquantum/core/measurement_test.py, src/setup.py
Creating a class for `Measurements` and reconciling overlap with `BitstringDistribution` class. 
This PR also affects the `QuantumSimulator` interface and therefore resources implementing this interface may need to be updated
=> 172411943 measurement class

src/python/zquantum/core/cost_function.py, src/python/zquantum/core/cost_function_test.py, src/python/zquantum/core/interfaces/backend.py, src/python/zquantum/core/interfaces/backend_test.py, src/python/zquantum/core/interfaces/cost_function.py, src/python/zquantum/core/interfaces/cost_function_test.py, src/python/zquantum/core/interfaces/mock_objects.py, src/python/zquantum/core/interfaces/optimizer_test.py
This PR makes a base set of tests that all classes implementing the `QuantumBackend` or `QuantumSimulator` interfaces need to satisfy.
=> 172420671 common tests

src/python/zquantum/core/cost_function.py, src/python/zquantum/core/estimator.py, src/python/zquantum/core/interfaces/cost_function.py, src/python/zquantum/core/interfaces/estimator.py, src/python/zquantum/core/interfaces/mock_objects.py
This PR adds estimation terms to the cost_function.
=> Add estimation error terms to cost_function

src/python/zquantum/core/circuit/_circuit.py, src/python/zquantum/core/circuit/_circuit_test.py, src/python/zquantum/core/utils_test.py
Part of the story https://www.pivotaltracker.com/story/show/173183192
=> Port save_circuit_set and load_circuit_set

templates/graph.yaml
Update the templates to use the new graphs methods, and the use of seed (these were introduced in https://github.com/zapatacomputing/z-quantum-core/commit/5dd508935c5ddb68c77ebfee0c29b1991e13c746)
=> Dev graph templates

src/python/zquantum/core/utils.py, src/python/zquantum/core/utils_test.py
Added optional functionality to insert a name for a list artifact when saving.
=> Adding option to name a list-type artifact

templates/measure.yaml
Adding a template to get bitstring distribution of a given circuit.
Maybe it's defined somewhere else already but couldn't find it 🤷‍♀️
=> Get wavefunction

src/python/zquantum/core/circuit/_circuit.py, src/python/zquantum/core/circuit/_circuit_test.py, templates/circuit.yaml
This PR adds the capability to extend an existing circuit adding to it a register of ancilla qubits. 
Maybe this could be useful for other people!
=> Add register

src/python/zquantum/core/utils_test.py
PR is meant to trigger cicd system
=> Formatting with black

templates/circuit.yaml
This PR adds a template to combine elements of a circuitset to create a composite circuit.
=> adding template to combine circuits

src/python/zquantum/core/history/recorder.py, src/python/zquantum/core/interfaces/functions.py, src/python/zquantum/core/interfaces/functions_test.py
This adds the possibility of adding a gradient to functions that store artifacts.
=> Implement function_with_gradient helper

src/python/zquantum/core/serialization.py, src/python/zquantum/core/serialization_test.py
This implements new `save_optimization_results` function. As a side effect, a more general JSON Encoder implementation is added that should be able to handle most of our serializable objects.
=> Implement serializer and save_optimization_results function

src/python/zquantum/core/serialization.py, src/python/zquantum/core/serialization_test.py, src/python/zquantum/core/utils.py, src/python/zquantum/core/utils_test.py
This implements `load_optimization_results` function capable of decoding the output of `save_optimization_results`.
=> 175099277 move agnostic optimization functions to z quantum core

src/python/zquantum/core/hamiltonian.py, src/python/zquantum/core/hamiltonian_test.py, steps/operators.py, testing/v1/workflows/reorder-fermionic-modes.yaml
This PR adds a function and step for reordering the modes of interaction operators.
=> Fermion mode reordering

steps/measure.py
Adding support for dict inputs to more steps.
=> More dict inputs

src/python/zquantum/core/openfermion/_io.py, src/python/zquantum/core/openfermion/_io_test.py
Adding function which outputs the pauli strings of a qubit operator.
=> Adding function to output Pauli strings of qubit operator

src/python/zquantum/core/circuit/conversions/cirq_conversions.py, src/python/zquantum/core/circuit/conversions/cirq_conversions_test.py
This implements converting Cirq gates to and from native Orquestra gates.
This PR does not implement support for converting Custom Gates and modifiers such as Control and Dagger; I will provide those in separate PR once this gets merged.
=> 174266178 cirq conversions

src/python/zquantum/core/circuit/__init__.py, src/python/zquantum/core/circuit/conversions/cirq_conversions.py, src/python/zquantum/core/circuit/conversions/cirq_conversions_test.py, src/python/zquantum/core/circuit/conversions/pyquil_conversion_test.py, src/python/zquantum/core/circuit/conversions/pyquil_conversions.py, src/python/zquantum/core/circuit/conversions/symbolic/sympy_expressions.py, src/python/zquantum/core/circuit/gates/__init__.py, src/python/zquantum/core/circuit/gates/_two_qubit_gates.py
This adds XY gate implementation and respective conversions to and from cirq and pyquil.
=> 176680489 add xy gate

src/python/zquantum/core/wip/circuit/conversions2/pyquil_conversions.py, src/python/zquantum/core/wip/circuit/conversions2/pyquil_conversions_test.py
This PR reimplements circuit conversion between ZQuantum & PyQuil. The PR contains work done partially by me and @dexter2206, including:
- non-parametric built-in gates
- parametric built-in gates
- non-parametric custom gates
- parametric custom gates
- daggers
- controlled gates
=> PyQuil conversions

src/python/zquantum/core/estimator.py, src/python/zquantum/core/estimator_test.py
This allows other estimators to easily use optimal shot allocation without duplicating code.
=> Refactored optimal shot allocation as a separate function

.flake8, .pre-commit-config.yaml
Minimal pre-commit that its 100% compatible with GitHub Actions currently
=> minimal precommit for actions 

src/python/zquantum/core/wip/circuits/__init__.py, src/python/zquantum/core/wip/circuits/_serde.py, steps/evaluation.py, steps/measure.py, tests/zquantum/core/wip/circuits/_serde_test.py
Includes helpers that leverage `ensure_open` for load/save without `if`s.
=> Migrate evaluation step

src/python/zquantum/core/history/example_functions.py, src/python/zquantum/core/history/recorder.py, tests/zquantum/core/history/recording_functions_with_gradient_test.py
This implements recording of gradient's history if `recorder` is used on function with gradient.
=> Add gradient recording

.coveragerc
=> Zqs 870/track backend usage

src/python/zquantum/core/interfaces/backend_test.py, src/python/zquantum/core/interfaces/optimizer_test.py
test_run_circuit_and_measure_correct_num_measurements_attribute had another equivalent test.
=> fix(backend_test): deleted duplicate test
