- src/python/zquantum/core/estimator.py
- src/python/zquantum/core/estimator_test.py
- src/python/zquantum/core/interfaces/backend.py
- src/python/zquantum/core/interfaces/estimator_test.py
- src/python/zquantum/core/interfaces/mock_objects.py
- src/python/zquantum/core/measurement.py
- src/python/zquantum/core/measurement_test.py
Updates the `BasicEstimator` to handle non-diagonal operators by applying context selection gates. Each term is computed in a separate circuit; grouping will be implemented in future PRs.
> Context selection

- src/python/zquantum/core/interfaces/ansatz_utils_test.py
This adds missing tests for `invalidates_parametrized_circuit`.
Additionally, this fixes some minor issues (typos, lack of docstrings) in previous tests that I wrote.
> Add missing tests

- src/python/zquantum/core/interfaces/mock_objects.py
- src/python/zquantum/core/interfaces/optimizer.py
- src/python/zquantum/core/interfaces/optimizer_test.py
This adds the `optimization_result` convenience function that should serve as an additional, static safety layer for constructing instances of `scipy.optimize.OptimizeResult` while ensuring it has the required fields set. 
See accompanying tests for usage examples.
Several notes:
- I thought about calling this `create_optimization_result` but decided to go for a shorter name for the following reasons:
- `create` is kind of an empty word (like get or set)
- it is more in line with names used through scientific libraries (e.g. you have `numpy.array` not `numpy.create_array`)
Please feel free to suggest a better name if you have one :)
- Tests don't check if you have to pass optimized value and params as keyword arguments, because it is already checked by the static type checker. Test in …
> Add the optimization_result function.

- src/python/zquantum/core/estimator.py
- src/python/zquantum/core/estimator_test.py
- src/python/zquantum/core/interfaces/estimator.py
- src/python/zquantum/core/interfaces/estimator_test.py
These changes make the logger at the module level, which is the Pythonic way of doing logging.
We also make the logging helper function a static method since it does not depend on instance variables.
(There is a single unrelated change: we add `EnforceOverrides` to the `Estimator` abstract base class).
> Make logger in Estimator at the module level.

- src/python/zquantum/core/bitstring_distribution/distance_measures/distance_measures_test.py
- src/python/zquantum/core/bitstring_distribution/distance_measures/jensen_shannon_divergence.py
Adding the jensen shannon divergence to the list of distance measures. It symmetrizes the clipped log likelihood
> Symmetrized loglikelihood

- templates/circuit.yaml
This PR adds 2 templates: 
1. combine 4 circuit artifacts in a circuitset  
2. add a circuit artifact to an existing circuitset 
Template 2 allows to create bigger circuitsets (more than 4 circuits). 
To me, the ideal way to go here would be to keep in the resource only template 2, and run it in a loop (in the workflow) so to update the circuitset with one circuit at a time, namely: 
```
name: loop-over-circuits
steps:
- - name: add-circuit-artifact-to-circuit-set
arguments:
- circuit-set: *the one from the previous loop step*
- circuit: item 
withItems: [circuit1, circuit2]
```
This seems not to be possible because the input of step n is the output of step n-1, and as far as I know this is not possible to do in the workflow. I looked into argo docs and some examples + thought about some …
> Build circuitset

- src/python/zquantum/core/utils.py
- src/python/zquantum/core/utils_test.py
This reimplements ValueEstimate as a subclass of float. This is backwards compatible, as new `ValueEstimate` still exposes `value` attribute (although marked as deprecated).
> Reimplement ValueEstimate as a subclass of float

- src/python/zquantum/core/interfaces/optimizer.py
- src/python/zquantum/core/interfaces/optimizer_test.py
This adapts optimizer interface to new history recording mechanism (which does not need a `CostFunction` objects). The base class for optimizer tests is also updated so the function being optimized are also callables with gradients as opposed to Cost functions.
> Adapt optimizer interface to new history recording mechanism

- src/python/zquantum/core/history/artifact_storage_test.py
- src/python/zquantum/core/history/example_functions.py
- src/python/zquantum/core/history/recorder.py
- src/python/zquantum/core/history/recording_functions_test.py
- src/python/zquantum/core/history/recording_functions_with_gradient_test.py
- src/python/zquantum/core/history/save_conditions.py
This converts docstrings in `history` package to Google-style ones (see [Google Python Style Guide](https://google.github.io/styleguide/pyguide.html).
> 175497446 make docstrings consistent across codebase

- src/python/zquantum/core/circuit/conversions/pyquil_conversion_test.py
- src/python/zquantum/core/circuit/conversions/pyquil_conversions.py
- src/python/zquantum/core/circuit/conversions/symbolic/sympy_expressions.py
- src/python/zquantum/core/circuit/conversions/symbolic/sympy_expressions_test.py
This is a (hopefully) final step in our efforts to implement the conversion of arbitrary Orquestra gates to PyQuil gates.
At this stage, it should be possible to convert an Orquestra gate to PyQuil gate even if it contains symbolic parameters. The symbolic parameters are also collected, i.e. appropriate variable declarations are also added to the corresponding PyQuil program in which context's the conversion is happening.
> 175538989 add support for converting parametrized gates

- src/python/zquantum/core/circuit/conversions/pyquil_conversion_test.py
- src/python/zquantum/core/circuit/conversions/pyquil_conversions.py
- src/python/zquantum/core/circuit/conversions/symbolic/pyquil_expressions.py
- src/python/zquantum/core/circuit/conversions/symbolic/pyquil_expressions_test.py
- src/python/zquantum/core/circuit/conversions/symbolic/sympy_expressions.py
- src/python/zquantum/core/circuit/conversions/symbolic/sympy_expressions_test.py
- src/python/zquantum/core/circuit/conversions/symbolic/translations_test.py
This implements translating PyQuil expressions into Sympy expressions. Included are:
- Single-dispatch function for constructing intermediate tree representation of PyQuil expression.
- SYMPY_DIALECT for use with `translate_expression`
Additionally, the structure of already present translation tests is flattened (the classes were used to group tests together, which is no longer needed because we split the translation module into several smaller ones).
> 175540559 pyquil expressions to orquestra expressions

- src/python/zquantum/core/circuit/conversions/pyquil_conversion_test.py
- src/python/zquantum/core/circuit/conversions/pyquil_conversions.py
- src/python/zquantum/core/circuit/gates/_dagger_test.py
- src/python/zquantum/core/circuit/gates/_gate.py
- src/python/zquantum/core/circuit/gates/_two_qubit_gates.py
This adds conversion of basic gates from PyQuil to Orquestra and simplifies already present conversion tests.
Changes from this PR don't include
- Conversion of custom gates
- Conversion of a whole program
- Proper docstrings
The above mentioned missing parts will be added in the next PR.
> 175540559 implement conversion from pyquil to orquestra

- src/python/zquantum/core/circuit/conversions/pyquil_conversion_test.py
- src/python/zquantum/core/circuit/conversions/pyquil_conversions.py
- src/python/zquantum/core/circuit/conversions/symbolic/helpers.py
- src/python/zquantum/core/circuit/conversions/symbolic/pyquil_expressions.py
- src/python/zquantum/core/circuit/conversions/symbolic/translations_test.py
The final step of conversion between PyQuil objects and orquestra objects. `convert_from_pyquil` variant implemented here allows for converting whole PyQuil program, including ones with custom gates.
> 175540559 converting pyquil custom gates and programs

- src/python/zquantum/core/openfermion/_utils.py
- src/python/zquantum/core/openfermion/_utils_test.py
I chatted with William about where this function should live. This pull request deprecates the previous pull request from pauli_circuit to dev, which can now be closed.
> Adding function to convert QubitOp to list of Pauli string gate circuits

- steps/circuit.py
Workflows using the `generate_random_ansatz_params` can now provide the ansatz specs as a dict instead of string. See [updated VQE example](https://github.com/zapatacomputing/z-quantum-vqe/blob/e1e68d04203d695d6527903ca468e66f47e62b73/examples/hydrogen-vqe.yaml#L149-L154).
> Ansatz specs can now be provided as dict instead of string

- src/python/zquantum/core/circuit/__init__.py
- src/python/zquantum/core/circuit/circuit/_circuit_test.py
- src/python/zquantum/core/circuit/conversions/pyquil_conversions.py
- src/python/zquantum/core/circuit/gates/_gate.py
- src/python/zquantum/core/circuit/gates/_gate_test.py
- src/python/zquantum/core/circuit/gates/_single_qubit_gates.py
- src/python/zquantum/core/circuit/gates/_single_qubit_gates_test.py
- src/python/zquantum/core/circuit/gates/_two_qubit_gates.py
- src/python/zquantum/core/circuit/gates/_two_qubit_gates_test.py
This speeds up evaluation of gates and circuits by performing substitution on gate parameters instead of the whole matrix.
As a side effect, new property `params` is added to each gate and initializers of individual gate subclasses are uniformized and now have signatures of `(qubit1, qubit2, ..., qubitn, param1, param2, ....paramk)` (possibly with different argument names).
This PR does not touch `CustomGate`, as separate work is being done to refactor them.
> 176345709 speedup circuit and gates evaluation

- docker/z-quantum-default/0.0.6/Dockerfile
- setup.py
- src/python/zquantum/core/measurement.py
- src/python/zquantum/core/measurement_test.py
- src/python/zquantum/core/utils.py
- src/setup.py
This PR removes grove as a dependency, since it was only being used for one small function. Note that although I removed grove from the `z-quantum-default` dockerfile, the dockerfile currently does not build for unrelated reasons.
> Remove dependency on grove

- docker/z-quantum-julia/Dockerfile
Bumping Julia to v1.5 and fixing the symlink. Julia is now installed in /root rather than /app, in line with what z-quantum-default does.
FIRST ZAPATA PR
> julia v1.5 dockerfile

- steps/operators.py
- steps/operators_test.py
This is fixing a bug I just introduced in the new qubit list concatenation function. I'm also adding a test to avoid future issues...
> qubit list concatenation fix

- src/python/zquantum/core/circuit/gates/_gate.py
- src/python/zquantum/core/circuit/gates/_single_qubit_gates_test.py
- src/python/zquantum/core/circuit/gates/_two_qubit_gates.py
- src/python/zquantum/core/circuit/gates/_two_qubit_gates_test.py
This adds textual representation (`__str__` and `__repr__` methods) for builtin-gate classes. 
The representation should look like an initializer call, in which all gate params except qubits are passed as keyword arguments e.g. `"X(0)"`, `"XX(2, 3, angle=pi)"` etc.
> Reworked gates representation

- src/python/zquantum/core/wip/circuit/_circuit2_test.py
- src/python/zquantum/core/wip/circuit/_gates.py
- src/python/zquantum/core/wip/circuit/_gates_test.py
- Calling a gate returns a `GateOperation` that contains information about the applied gate and what qubit indices the gate is to be applied to.
- The PR also contains a Circuit class without (de)serialization support. I'd like to tackle the serialization in another PR.
> Gate Operations decoupled from gates

- src/python/zquantum/core/wip/circuit/_gates.py
- src/python/zquantum/core/wip/circuit/conversions2/qiskit_conversions.py
- src/python/zquantum/core/wip/circuit/conversions2/qiskit_conversions_test.py
Improvement over #225 that adds conversion for non-parametrized custom gates:
- ZQuantum's custom gate defined via a `CustomGateDefinition` is exported as [Qiskit's Unitary gate](https://qiskit.org/documentation/stubs/qiskit.extensions.UnitaryGate.html)
- Any Qiskit gate we don't have a mapping for is translated to a custom gate
We don't support converting custom parametrized gates, because:
- in case of an export – I couldn't find a way to create a parametrized custom gate in Qiskit. There's a chance it will be added to Qiskit in the future, though (see [the issue](https://github.com/Qiskit/qiskit-terra/issues/4751)).
- in case of an import – when we import a gate without an explicit mapping we rely on getting the gate matrix from Qiskit. …
> Import+export for custom gates in Qiskit

- src/python/zquantum/core/wip/circuits/_compatibility.py
- tests/zquantum/core/wip/circuits/_compatibility_test.py
Currently, converting old circuit to new (wip) circuit discards inactive qubits past the last active qubit. This is because we used old -> Cirq -> new conversion strategy, and already old -> Cirq part loses those inactive qubits.
This PR fixes this by checking the old circuit for the qubit with the largest index and then explicitly setting `n_qubits` in the new circuit.
> Fix handling inactive qubits past last active qubit

- .flake8
- .github/workflows/style.yml
- src/python/zquantum/core/cost_function.py
- src/python/zquantum/core/evolution.py
- src/python/zquantum/core/measurement.py
- src/python/zquantum/core/utils.py
I've ran the same check that Github Actions do and fixed the errors for a couple of first files on the list.
Moreover, I've added [W503](https://www.flake8rules.com/rules/W503.html) to the list of rules ignored by `flake8` because this rule contradicts `black`'s output.
The command to replicate the errors locally is: 
```
flake8 --ignore=E203,E266,F401,W503 --max-line-length=88 src
```
Lastly, please take a look at https://github.com/zapatacomputing/z-quantum-core/blob/8b2a05f070e13af8f7a92934615c59079e3bde4b/src/python/zquantum/core/cost_function.py#L46-L53 – I aliased the default value because otherwise the line would be too long. Running `black` on the file didn't fix it so I've came up with this workaround but it doesn't seem idiomatic. Perhaps you have a better idea?
> Fix flake8 errors (vol. 1)

- src/python/zquantum/core/circuit/_circuit_template.py
- src/python/zquantum/core/interfaces/ansatz_utils.py
- src/python/zquantum/core/serialization.py
- steps/circuit.py
- steps/optimize.py
- tests/acceptance_tests/operators_test.py
- tests/acceptance_tests/optimize_test.py
- tests/zquantum/core/circuit/_circuit_template_test.py
- tests/zquantum/core/interfaces/ansatz_utils_test.py
Note: this breaks backwards compatibility with `optimize` steps artifacts - the schema for `load_circuit_template_params` and `save_array` is different.
> Remove references to old circuits from circuit & optimize steps

- src/python/zquantum/core/interfaces/optimizer.py
- src/python/zquantum/core/interfaces/optimizer_test.py
- tests/zquantum/core/interfaces/optimizer_utils_test.py
This PR enforces recording of gradient history by every implementer of Optimizer interface. Also, it includes small refactors in Optimizer tests.
> Add gradient history recording

- steps/measure.py
Fixes the error when using `measure` step in a workflow:
```
"/app/qeruntime/python3/run", line 253, in run_command
[runtime] 2021-06-07T13:12:16.541Z     return py_function(**kwargs)
[runtime] 2021-06-07T13:12:16.541Z   File "/app/step/z-quantum-core/steps/measure.py", line 80, in run_circuitset_and_measure
[runtime] 2021-06-07T13:12:16.541Z     circuit_set = circuits.load_circuit_set(circuitset)
[runtime] 2021-06-07T13:12:16.541Z Traceback (most recent call last):
[runtime] 2021-06-07T13:12:16.542Z AttributeError: module 'zquantum.core.circuits' has no attribute 'load_circuit_set'
```
> Fix typo in measure step

- setup.py
- src/python/zquantum/core/circuits/symbolic/sympy_expressions.py
Some projects couldn't be migrated to use the new circuits because of dependency conflict on sympy version. This PR makes z-quantum-core compatible with both sympy 1.5 and >=1.6.
Turns out circuit conversions was the only affected place that I found. In the future, if we have more functionality that would break when using `sympy==1.5` we would probably have to use workarounds similar to the one proposed in this PR.
cc @martamau @simonwa7.
> Compatibility with older sympy version

- src/python/zquantum/core/distribution/_measurement_outcome_distribution.py
If a bitstring is of type Tuple[np.int32, ...], the `is_measurement_outcome_distribution` check at initialization of `BitstringDistribution` will fail because `_are_keys_non_negative_integer_tuples` returns `False`. The reason is that `numpy.integer` instances are not instances of `int`.
See https://stackoverflow.com/a/37727662
> check validity of bitstring against np.integer type not native int type

- docker/z-quantum-julia/Dockerfile
We need to bump to julia 1.7 for some of @ghazivakili 's work. It hasn't been built in over a year so it's due for a refresh. I'm pretty sure a merge into main will trigger a rebuild in concourse
> bump z-quantum-julia to 1.7.2
